# Travis CI (MIT License) configuration file for http://change.connorbaer.io.
# @link https://travis-ci.org/

# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: ruby

# Declare versions of Ruby to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        - rvm: 'ruby-head'
          env: SNIFF=1
        - rvm: '2.3'
          env:
              - SNIFF=2
              # speeds up installation of html-proofer
              - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

    allow_failures:
        - rvm: '2.3'

gemfile:
    - gemfile

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
    # Install JSHint, a JavaScript Code Quality Tool.
    # @link http://jshint.com/docs/
    - if [[ "$SNIFF" == "1" ]]; then npm install -g jshint
    # Install JSCS: JavaScript Code Style checker.
    # @link http://jscs.info/
    - if [[ "$SNIFF" == "2" ]]; then npm install -g jscs

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
    #!/usr/bin/env bash

    # Build the website.
    - bundle exec jekyll build
    # Run the website through JSHint.
    - if [[ "$SNIFF" == "1" ]]; then jshint .
    # Run the website through JavaScript Code Style checker.
    - if [[ "$SNIFF" == "2" ]]; then jscs .
    # Run the website through htmlproofer.
    - if [[ "$SNIFF" == "2" ]]; thenbundle exec htmlproofer ./_site --check-favicon --check-html

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email:
        email:
            - admin@connorbaer.io
