# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
color:                '#000'
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /:title/


# Site meta
title:                'Change'
tagline:              'Embrace change.'
description:          'Change is a minimalist Jekyll theme built by <a href="http://connorbaer.io/" title="Follow Connor Bär on Twitter.">Connor Bär</a>.'
keywords:             'connor, baer, bear, designer, developer, traveller, design, code, jekyll, change, theme, for hire'
url:                  http://change.connorbaer.io
baseurl:              ''
assets:               /assets
images:               /images/
logo:                 /assets/icons/apple-icon-144x144.png

author:
  name:               Connor Bär
  bio:                Hi, I'm Connor, the author of this blog. Nice to meet you!
  image:              author
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

social:
  twitter:            https://twitter.com/connor_baer
  instagram:          https://instagram.com/connor_baer
  github:             https://github.com/connor-baer/change
  medium:             https://blog.connorbaer.io

version:              3.1

github:
  repo:               https://github.com/connor-baer/change


# Integrations
typekit:              fcv7rfe

# google_fonts:
#   name:             weights

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

facebook:
  app_id:             169140053203395
