# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
color:                '#fff'
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile]
permalink:            /:title/


# Site meta
title:                'Change.'
tagline:              'Change is a minimalist Jekyll theme built by @connor_baer.'
keywords:             'connor, baer, bear, designer, developer, traveller, design, code, jekyll, change, theme, for hire'
description:          'Change is a minimalist Jekyll theme built by @connor_baer.'
url:                  http://change.connorbaer.io
baseurl:              ''
logo:                 /assets/icons/apple-icon-144x144.png
twitter:
  username:           connor_baer
facebook:
  app_id:             169140053203395

# google_analytics_key: UA-37412525-4 
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name:               Connor Bär
  url:                http://connorbaer.io
  email:              hello@connorbaer.io
  twitter:            connor_baer

social:
  name:               Connor Bär
  links:              
    - https://twitter.com/connor_baer
    - https://instagram.com/connor_baer
    - https://github.com/connor-baer
    - https://medium.com/@connor_baer

nav:
  1. about:           '/#about'
  2. blog:            '/#blog'
  3. Use:             '/#use'

mobile: 
  about:           '/#about'

version:              2.0.0

github:
  repo:               https://github.com/connor-baer/change
